[devops_servers]
devops-server ansible_host=35.154.228.47 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ubaidahmed.pem

[devops_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
